# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by setup_project
# This file reflects the paths in the primary pipeline
# configuration defined for this project.

Windows: 'C:\repo\tk-config-alpha\tk-config-alpha'
Darwin: ''
Linux: ''

# End of file.
