# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by setup_project
# This file reflects the paths in the primary pipeline
# configuration defined for this project.

Windows: 'Z:\SHOTGUN\configurations\craterdefault'
Darwin: ''
Linux: ''

# End of file.
